config/routes.rb
Rails.application.routes.draw do
  get 'profiles' => 'profiles#index'

  get 'profiles/:id' => 'profiles#show', as: :profile

  devise_for :users

  resources :tweets do
    resource :likes
  end

  resources :relationships

  root 'tweets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes

  validates :user_id, presence: true
  validates :user, presence: true
  validates :message, presence: true, length: {maximum: 140, too_long: 'A tweet can only be a hundred and forty characters, max.'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
  has_many :likes
  has_many :relationships
  has_many :friends, through: :relationships

  has_many :inverse_relationships, class_name: 'Relationship', foreign_key: 'friend_id'
  has_many :inverse_friends, through: :inverse_relationships, source: :user

  validates :username, presence: true, uniqueness: true

  def likes?(tweet)
    tweet.likes.where(user_id: id).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit({ rolls: []  }, :email, :password, :password_confirmation, :name, :username, :bio, :location)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit({ rolls: []  }, :email, :password, :password_confirmation, :current_password, :name, :username, :bio, :location) }

  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet

  def create
    @tweet.likes.where(user_id: current_user.id).first_or_create

    respond_to do |format|
      format.html { redirect_to request.referrer}
    end
  end

  def destroy
    @tweet.likes.where(user_id: current_user.id).destroy_all

    respond_to do |format|
      format.html {redirect_to request.referrer }
    end
  end

  private

  def set_tweet
        @tweet = Tweet.find(params[:tweet_id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @friend = User.find(params[:friend_id])
    @relationship = current_user.relationships.build(friend_id: @friend.id)

      if @relationship.save
        flash[:notice] = "You're now following #{@friend.username}"
        redirect_to profile_path(@friend.id)
      else
        flash[:notice] = "something went wrong, try again please!"
        redirect_to profile_path(@friend.id)
      end
    #  if
  end
# create

def destroy
  @relationship = current_user.relationships.find(params[:id])
  @relationship.destroy

  flash[:notice] = 'No longer following.'
  redirect_to profile_path(current_user.id)
end

private

  def relationship_params
    params.require(:relationship).permit(:user_id, :friend_id)

  end
# relationship params


end
# class

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

    def index
      @tweets = Tweet.all
    end

    def show
    end

    def edit
    end

    def update
      respond_to do |format|
        if @tweet.update(tweet_params)
          format.html { redirect_to @tweet, notice: 'Tweet was updated.' }
        else
          format.html { render :edit }
        end
        # of if
      end
      # of do
    end
    # of update

    def new
      @tweet = Tweet.new
    end

    def create
      @tweet = Tweet.new(tweet_params)

      respond_to do |format|
        if @tweet.save
          format.html { redirect_to @tweet, notice: 'Tweet was posted!'}
        else
          format.html { render :new }
        end
        # of if
    end
    # of do
  end
  # of create

  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html {redirect_to tweets_url, notice: 'Your tweet has been destroyed.'}
    end
  end

private

  def set_tweet
          @tweet = Tweet.find(params[:id])
  end


  def tweet_params
    params.require(:tweet).permit(:message, :user_id)
  end
  # of params
end
# of tweet controller

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twittable</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to fa_icon('sign-out', text: 'Sign Out'), destroy_user_session_path, method: :delete, class: 'btn btn-default btn-sm' %>

    <%= yield %>
  </body>
</html>

app/views/profiles/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
  <%= link_to user.username, profile_path(user) %>
<% end %>

app/views/profiles/show.html.erb
<div class="container-fluid">
  <div class="row">
    <!-- left side box -->
    <div class="col-xs-4">
      <h3><%= @user.name %></h3>
      <h5><%= @user.username %></h5>
      <h5><p><%= @user.bio %></p></h5>
      <h5>Joined on <%= @user.created_at.strftime("%B %Y") %></h5>

  <!-- people user is following -->
  <%= @user.relationships.count %> Following
  <br>
    <% @user.relationships.each do |relationship| %>
      <%= link_to relationship.friend.name, profile_path(relationship.friend) %>
      <br>
    <% end %>
    <br><br>

    <!-- followers -->
    <%= pluralize(@user.inverse_relationships.count, 'Follower') %>
    <br>
    <% @user.inverse_friends.each do |friend| %>
      <%= link_to friend.name, profile_path(friend) %>
      <br>
    <% end %>
  </div>


  <!-- right side box -->
    <div class="col-xs-7">
        <!-- all the users tweets -->
        <div class="panel panel-default">
          <% @user.tweets.each do |tweet| %>
            <div class="panel-body">
              <strong><%= tweet.user.username %></strong> <small>tweeted <%= time_ago_in_words(tweet.created_at) %> ago</small>
              <br><br>
              <%= tweet.message %>
            </div>
          <% end %>
        </div>

    </div>
  </div>


  <br><br>

<!-- follow and unfollow buttom -->
<% if current_user.id != @user.id %>
  <% if current_user.friends.include?(@user) %>  <!-- if you're already following, unfollow button -->
    <%= link_to "Unfollow", relationship_path(current_user.relationships.find_by_friend_id(@user)), method: :delete, class: 'btn btn-danger btn-sm' %>
  <% else %>  <!-- if you're not following, follow bottom -->
    <%= link_to "Follow", relationships_path(friend_id: @user.id), method: :post, class: 'btn btn-info btn-sm' %>
  <% end %>
<% end %>
<!-- follow and unfollow buttom -->
</div>

app/views/shared/_likes.html.erb
<% if current_user.likes?(@tweet) %>
<!-- unlike button -->
<%= link_to "Unlike", tweet_likes_path(@tweet), method: :delete, class: 'btn btn-sm btn-warning' %>
<% else %>

<%= link_to "Like", tweet_likes_path(@tweet), method: :post, class: 'btn btn-success btn-sm' %>

<% end %>
<br>

<%= pluralize(@tweet.likes.count, 'Like') %>
<br><br>
Likes by:
<% @tweet.likes.each do |like| %>
  <br>
    <%= like.user.username %>
  <br>
<% end %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>

<!-- checks for errors -->
<% if @tweet.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@tweet.errors.count, 'error') %> prohibited this tweet from being saved
  </h2>

  <!-- loop through the errors and show them as a list -->
  <ul>
    <% @tweet.errors.full_messages.each do |error_message| %>
      <li><%= error_message %></li>
    <% end %>
  </ul>

</div>

<% end %>

<!-- actual form -->

<div class="field">
  <%= f.label :message %> <br>
  <%= f.text_field :message %>
</div>

<div class="field">
  <%= f.label :user_id %> <br>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="actions">
  <%= f.submit %>
</div>

  <% end %>

app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>

<%= render 'form' %>

<%= link_to 'All the tweets you want to see AKA Home', tweets_path, class: 'btn btn-danger' %>

app/views/tweets/index.html.erb
<p id="notice"> <%= notice %> </p>

<h1>All the greatest tweets that ever lived</h1>

<%= link_to 'New Tweet', new_tweet_path, class: 'btn btn-warning' %>

<table class="table table-striped table-hover">
<!-- table head -->
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<!-- table body -->
  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message %></td>
        <td><%= tweet.user.username %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>


</table>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'All the tweets you want to see AKA Home', tweets_path, class: 'btn btn-danger' %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message: </strong> <%= @tweet.message %>
</p>

<p>
  <strong>User: </strong><%= @tweet.user.username %>
</p>

<%= render 'shared/likes' %>

<%= link_to 'Edit', edit_tweet_path(@tweet), class: 'btn btn-sm btn-default' %>
<%= link_to 'All The Tweets', tweets_path, class: 'btn btn-sm btn-default' %>